# Generated by Django 5.2.3 on 2025-06-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a short title', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Add a detailed description of the task', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='Optional: add a deadline', null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Indicates whether the To-Do item has been completed.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
